# Generated by Django 6.0.1 on 2026-01-15 23:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='аголовок')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog/previews/', verbose_name='ревью')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ата создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='ризнак публикации')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='оличество просмотров')),
            ],
            options={
                'verbose_name': 'логовая запись',
                'verbose_name_plural': 'логовые записи',
                'ordering': ['-created_at'],
            },
        ),
    ]
